
spring:
  mqtt:
    host: tcp://121.40.140.223:1883
    clientId: 1
    topic: /boxcloud/KBOXTEST0002/custom/data/point,/boxcloud/KBOXTEST0002/device/status
    username: zust-test
    password: zust123456
    timeout: 30
    keepalive: 30

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/electricity_consumption?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456

#  devtools:
#    restart:
#      enabled: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zust.entity
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8090




